---
- name: enable firewall
  hosts: control_node
  gather_facts: yes
  become: yes
  tasks:
    - name: ensure firewall is installed (ubuntu)
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: ensure firewall is inatelled (centos)
      ansible.builtin.yum:
        name: firewalld
        state: present
      when: ansible_distribution == "CentOS"

    - name: enable firewall (ubunt)
      ufw:
        state: enabled
      when: ansible_distribution == "Ubuntu"

    - name: allow ssh (ubuntu)
      ufw:
        rule: allow
        port: '22'
        proto: tcp
      when: ansible_distribution == "Ubuntu"

    - name: allow http (ubuntu)
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_distribution == "Ubuntu"

    - name: allow https (ubuntu)
      ufw:
        rule: allow
        port: '443'
        proto: tcp
      when: ansible_distribution == "Ubuntu"

    - name: enable firewall (Centos)
      service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_distribution == "CentOS"

    - name: allow ssh (centos)
      firewalld:
        service: ssh
        permanent: true
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: allow http (centos)
      firewalld:
        service: http
        permanent: true
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: allow https (centos)
      firewalld:
        service: https
        permanent: true
        state: enabled
      when: ansible_distribution == "CentOS"
      
    - name: reload firewall (ubuntu)
      ufw:
        state: reloaded
      when: ansible_distribution == "Ubuntu"

    - name: reload firewall (CentOS)
      command: firewall-cmd --reload
      when: ansible_distribution == "CentOS"
